### ISSUE TITLE
管理者が出荷をwebから指示できるようにしてください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-web#23]
webで管理者がパレット出荷をクリックすることで出荷完了。
出荷の指示する日と出荷日は異なる（大体は前日に出荷指図）ので
出荷日は設定できるようにしてください。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 出荷完了のみのものに
制作日、準備完了日、出荷日を変更可能にしたいですがよろしいですか？システムロジックの問題です

**Comment by tsubasamatsumoto** [comment]
制作日、準備完了日、出荷日、出荷ステータス変更は詳細から変えるの？
詳細は台車に入っているロールだけ表示して変更は一覧の画面から変えた方が楽じゃないですか？

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 制作日、準備完了日、出荷日は変更可能にします。
ステータスは右上の「...」のみです。
一覧での変更は管理画面で対応してないです。全ての変更は詳細から行います

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 変更可能にしました

**Comment by tsubasamatsumoto** [comment]
OK
