### ISSUE TITLE
管理者が出荷指示をしたときに出荷リストが出るようにしてください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-web#24]
出荷リストがでるようにしてください。フォーマットはPDFでもエクセルでも構いません。
参考情報：出荷リストは営業、お客さんに配っています。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto データなど追加しました。ご確認ください

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 出荷画面で出荷詳細を開いて、出荷済みの場合は右上で印刷ボタンが表示されます。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました

**Comment by tsubasamatsumoto** [comment]
確認しました。いい感じ。
リストを検索するとき12/5～12/5など1日はできない？

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 入りました

**Comment by tsubasamatsumoto** [comment]
OK、対応ありがとうございます。
