### ISSUE TITLE
日報を作成出来るようにしてください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-web#28]

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto フォーマットをください。

**Comment by tsubasamatsumoto** [comment]
[格上げ.xlsx](https://github.com/DecodeLLC/seiren-web/files/1313829/default.xlsx)

**Comment by tsubasamatsumoto** [comment]
[日報.pdf](https://github.com/DecodeLLC/seiren-web/files/1313915/default.pdf)

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto こんな感じです。
https://s3-ap-northeast-1.amazonaws.com/storage.seiren.decodeapps.io/cc6a3a10ac2522593524bc6a31491700e9f0390e.pdf

**Comment by tsubasamatsumoto** [comment]
欠点の項目は項目名を『主欠点』、備考１は項目名を『その他欠点』にしてください。
その他欠点には検査で入力された欠点名をすべて入力してください。
備考２は『備考』に項目名を変更。
この日報はCSVで出力できるようにしてください。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto こちらは項目ごとに説明していただけますか？

**Comment by tsubasamatsumoto** [comment]
[Book16.xlsx](https://github.com/MaruiorimonoTeam/seiren-web/files/1534431/Book16.xlsx)

**Comment by tsubasamatsumoto** [comment]
わからないことがあれば聞いてください。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto いかがですか？
https://s3-ap-northeast-1.amazonaws.com/storage.seiren.decodeapps.io/2c3539041ae01a6b8778fda2089c962b804f4293.csv

**Comment by tsubasamatsumoto** [comment]
区切りを；（セミコロン）から、,（カンマ）に変更してほしい。
目的はエクセルでCSVを開いたときに区切りの設定変更無しで、自動的に区切ってくれるから。
ただしその他欠点の欠点同士の区切りは；（セミコロン）のままでOKです。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto ご確認ください
https://s3-ap-northeast-1.amazonaws.com/storage.seiren.decodeapps.io/d1541518a333436ee0d970ea027787df94183ae2.csv

**Comment by tsubasamatsumoto** [comment]
フォーマットOKです。

**Comment by tsubasamatsumoto** [comment]
確認してほしいものがあります。
①品番を加工品番にしてください。
②全幅欠点がないのに全幅欠点ありになるものがある。（反No.91129314-1-2など）
③全幅欠点があるのに全幅欠点なしになるものがある。（反No.91129314-1　織機0314-08）

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。ご確認ください
