### ISSUE TITLE
週報、月報を作成できるようにしてください

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-web#29]
期間でソートして出力。出力はPDF、CSV。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto フォーマットをください

**Comment by tsubasamatsumoto** [comment]
[月報.xlsx](https://github.com/DecodeLLC/seiren-web/files/1313822/default.xlsx)

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto こんな感じです。
https://s3-ap-northeast-1.amazonaws.com/storage.seiren.decodeapps.io/7f6fdb1d602e77f5e54de0e555bad0cad38e10d5.pdf

**Comment by tsubasamatsumoto** [comment]
C反率はC反疋数／加工疋数の％で出してください。

C反疋数は検査でD、Eとランク付けしたものです。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto こちらの上の部分は格上げと何が違いますか？

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto いかがですか？
https://s3-ap-northeast-1.amazonaws.com/storage.seiren.decodeapps.io/d0693442c2b53b972995b2cfa4a40a9669481a0e.pdf

**Comment by tsubasamatsumoto** [comment]
@alexeypolitov  OK。この表にC反の率もつくんだよね？
（月報.xlsxの下の表）

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto ウェブでもご確認ください。
<img width="390" alt="screen shot 2017-12-08 at 11 20 43" src="https://user-images.githubusercontent.com/3468058/33748070-da7a73ea-dc09-11e7-80af-541a81fc7a6e.png">

**Comment by tsubasamatsumoto** [comment]
１つ集計方法で訂正したいことがあります。
格上げしたものの集計方法です。
ユーザーが指定した期間内に格上げされているものは、合格＝Ａ反としてカウントしてほしいです。
大変申し訳ないですがお願いします。

**Comment by tsubasamatsumoto** [comment]
エクセルも出力できますか？

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto CSVでしたら出せます

**Comment by tsubasamatsumoto** [comment]
PDFとCSVのどちらか選択して出すようにはできますか？

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 追加しました

**Comment by tsubasamatsumoto** [comment]
検査月報が日付を変えると出力されません。確認おねがいします。
