### ISSUE TITLE
格上げ処理できるようにしてください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-web#35]

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto こちらは何のことですか？

**Comment by tsubasamatsumoto** [comment]
https://github.com/DecodeLLC/seiren-ios/issues/85

この作業で保留としたときに、WEBではDとなりますが、印刷されラベル検査表のランク部は空白とします。
管理者がDをAにランクをアップさせる時（社内で手続きを踏んでからですが）、ウェブからDランクをAランクに変更出来るようにしてほしいです。またそのときは格上げしたとの履歴も分かるようにしてほしいです。
ちなみに印刷されたラベル、検査表のランクの空白部は後で管理者が手書きでランクを記入し出荷します。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto こちらはランキングなどを変更してから、QR＆検査表を再印刷できればいいとういうことですか？

**Comment by tsubasamatsumoto** [comment]
ランキング変更後、再印刷できれば嬉しいです。
今は手書きで修正を考えていました。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 精錬情報、検査情報、再印刷は可能です。ご確認ください

**Comment by tsubasamatsumoto** [comment]
電話のときのメモ
格上げ：ランクA以外のランクをAへ変更する処置。この処置を行った場合、その履歴が分かるように
期間でソートしその一覧がでるように、印刷出来るようにする必要がある。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 格上げ処理できるようにしました。ロールの右上の「...」格上げ処理可能の場合はメニューが表示されます

**Comment by tsubasamatsumoto** [comment]
ロールの右上の「...」を押して格上げする際、確認での「削除」を「Aに変更」というのに変えてください。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto はい、エンジニアが日本語をcopy&pasteしたので、終わったら全体的に直しますw

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。ご確認ください

**Comment by tsubasamatsumoto** [comment]
OK
