### ISSUE TITLE
精錬日報（ロット作成日報）が作成できるようにしてください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-web#37]
[精錬日報.xlsx](https://github.com/DecodeLLC/seiren-web/files/1313906/default.xlsx)

**Comment by tsubasamatsumoto** [comment]
https://github.com/MaruiorimonoTeam/seiren-web/issues/28

これと同じ機能で、CSV出力ができるようにしてください。

**Comment by tsubasamatsumoto** [comment]
![img_5418](https://user-images.githubusercontent.com/19566850/33652104-7ebb37ce-daab-11e7-9db2-50fe42c4f369.JPG)

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto こういう感じでいかがですか？
https://s3-ap-northeast-1.amazonaws.com/storage.seiren.decodeapps.io/248f30e5ac2963fa0557567ba17c5f758cf0a9b5.csv

**Comment by tsubasamatsumoto** [comment]
フォーマットはOK。
区切りを；（セミコロン）から,（カンマ）に変えてほしい。
ここの反番は織布での反番（バーコドのラベルに記載）になります。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 
https://s3-ap-northeast-1.amazonaws.com/storage.seiren.decodeapps.io/170a6c4d6b91cf4a62a3a8c6f3d3a5cae1194583.csv

> ここの反番は織布での反番（バーコドのラベルに記載）になります。

こちらはどういう意味ですか

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto ウェブでご確認ください

**Comment by tsubasamatsumoto** [comment]
OK
