### ISSUE TITLE
ロールのタブで検索できる項目を追加してください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-web#44]
①ロットNo.
②検査日
③出荷日
④検査号機

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto ロール一覧のことですか？

**Comment by tsubasamatsumoto** [comment]
はい、ロールの一覧の部分でのことです。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 追加しました。ご確認ください

**Comment by tsubasamatsumoto** [comment]
ロットNo.って検索できるようになっている？

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto バグでした。修正しました

**Comment by tsubasamatsumoto** [comment]
ロットNoが検索できるようになっていることを確認しました。
もう１つ疑問。
②検査日、③出荷日の検索って検索方法（検索キーワド）が同じになるのでは？

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto はい、同じです

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto ご確認ください

**Comment by tsubasamatsumoto** [comment]
②検査日、③出荷日ってキーワドがかぶるのでわからないです。分けて検索できませんか？

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 例えば「検査日2017-12-31 出荷日2017-12-31」を入力してそろぞれで検索する仕組みでよかったら修正します。いかがですか？

**Comment by tsubasamatsumoto** [comment]
了解。その仕様でお願いします。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 追加しました。ご確認ください

**Comment by tsubasamatsumoto** [comment]
OK
