### ISSUE TITLE
出荷指示後のポップアップを日本語にしてください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [MaruiorimonoTeam/seiren-web#57]

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。ご確認ください

**Comment by tsubasamatsumoto** [comment]
まだ英語なので修正してください。
![image](https://user-images.githubusercontent.com/19566850/33828009-afb058ea-dead-11e7-989e-b43fd62554ad.png)

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto こういうエラーはエンジニア用です。一般ユーザーは見れないはずです。どのフローでこのエラーが表示されましたか？

**Comment by tsubasamatsumoto** [comment]
出荷で詳細をクリックして右上の『...』を押して出荷準備完了を押してもでるし、出荷完了を押してもでるよ。

**Comment by tsubasamatsumoto** [comment]
プラベートモードでチェックします。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 他の問題を修正しました

**Comment by tsubasamatsumoto** [comment]
プライベートモードでチェックしてもでました。
![image](https://user-images.githubusercontent.com/19566850/34040656-071b86e0-e1d8-11e7-89dc-3f3a21aa1183.png)

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。ご確認ください

**Comment by tsubasamatsumoto** [comment]
OK
